# Generated by Django 3.2.10 on 2021-12-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='descri',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default=0, upload_to='pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='offer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
